version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker0:
    image: confluentinc/cp-kafka:7.4.0
    hostname: broker0
    container_name: broker0
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker0:29092, PLAINTEXT_HOST://localhost:9092
      # KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"

  cli-tools:
    image: confluentinc/cp-kafka:7.4.0
    container_name: cli-tools
    entrypoint: "sleep infinity"
    restart: always