{
 "title": "Traffic Data",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total Traffic Volume Absolute",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "traffic_data",
     "rawSql": "SELECT COUNT(id) FROM traffic_data.traffic_info LIMIT 50"
    }
   ]
  },
  {
   "title": "Total Traffic Volume Past Half Hour",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "traffic_data",
     "rawSql": "SELECT \r\n    SUM(north_south_traffic) AS \"Total North-South Traffic\", \r\n    SUM(east_west_traffic) AS \"Total East-West Traffic\"\r\nFROM (\r\n    SELECT north_south_traffic, east_west_traffic\r\n    FROM traffic_data.traffic_stats\r\n    ORDER BY id DESC\r\n    LIMIT 10\r\n) AS subquery;"
    }
   ]
  },
  {
   "title": "Vehicle Traffic Direction",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "traffic_data",
     "rawSql": "SELECT north_south_traffic, recorded_time, east_west_traffic\r\nFROM (\r\n    SELECT north_south_traffic, recorded_time, east_west_traffic, id\r\n    FROM traffic_data.traffic_stats\r\n    ORDER BY id DESC\r\n    LIMIT 10\r\n) AS subquery\r\nORDER BY id ASC;"
    }
   ]
  },
  {
   "title": "Pedestrian Traffic Direction",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "traffic_data",
     "rawSql": "SELECT north_south_ped_count, recorded_time, east_west_ped_count\r\nFROM (\r\n    SELECT north_south_ped_count, recorded_time, east_west_ped_count, id\r\n    FROM traffic_data.pedestrian_stats\r\n    ORDER BY id DESC\r\n    LIMIT 10\r\n) AS subquery\r\nORDER BY id ASC;"
    }
   ]
  },
  {
   "title": "Jay Walkers",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "traffic_data",
     "rawSql": "SELECT jay_walkers_count, recorded_time\r\nFROM (\r\n    SELECT jay_walkers_count, recorded_time, id\r\n    FROM traffic_data.pedestrian_stats\r\n    ORDER BY id DESC\r\n    LIMIT 10\r\n) AS subquery\r\nORDER BY id ASC;"
    }
   ]
  },
  {
   "title": "Red Light Runners",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "traffic_data",
     "rawSql": "SELECT redlight_runner_count, recorded_time\r\nFROM (\r\n    SELECT redlight_runner_count, recorded_time, id\r\n    FROM traffic_data.traffic_stats\r\n    ORDER BY id DESC\r\n    LIMIT 10\r\n) AS subquery\r\nORDER BY id ASC;"
    }
   ]
  },
  {
   "title": "Speeding Vehicles",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "traffic_data",
     "rawSql": "SELECT speeding_vehicle_count, recorded_time\r\nFROM (\r\n    SELECT speeding_vehicle_count, recorded_time, id\r\n    FROM traffic_data.traffic_stats\r\n    ORDER BY id DESC\r\n    LIMIT 10\r\n) AS subquery\r\nORDER BY id ASC;"
    }
   ]
  }
 ]
}