global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "kafka"
    static_configs:
      - targets:
          - "broker0:9092"
          - "broker1:9093"
          - "broker2:9094"

  - job_name: "schema-registry"
    static_configs:
      - targets:
          - "schema-registry:8081"

  - job_name: "node_exporter"
    static_configs:
      - targets:
          - "node-exporter:9100"
